# Generated by Django 5.0.7 on 2024-07-24 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='VacancyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('vacancies', models.PositiveIntegerField(verbose_name='Вакансии')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Запись вакансии',
                'verbose_name_plural': 'Записи вакансий',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(verbose_name='Месяц')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('hired', models.PositiveIntegerField(default=0, verbose_name='Принято')),
                ('fired', models.PositiveIntegerField(default=0, verbose_name='Уволено')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Движение сотрудников',
                'verbose_name_plural': 'Движения сотрудников',
                'unique_together': {('city', 'month', 'year')},
            },
        ),
    ]
