# Generated by Django 5.0.7 on 2024-07-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_recruitmentfunnel_period_funnel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='status',
            name='movement',
        ),
        migrations.AlterModelOptions(
            name='recruitmentfunnel',
            options={'verbose_name': 'Отчетный период', 'verbose_name_plural': 'Отчетные периоды'},
        ),
        migrations.DeleteModel(
            name='Funnel',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
