# Generated by Django 5.0.7 on 2024-07-26 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_remove_period_movement_remove_status_movement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_stage', to='table.recruitmentfunnel', verbose_name='Отчетный период')),
            ],
        ),
        migrations.CreateModel(
            name='FunnelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.IntegerField(default=0)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_data', to='table.recruitmentfunnel', verbose_name='Отчетный период')),
                ('funnel_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.funnelstage')),
            ],
            options={
                'unique_together': {('funnel_stage', 'date')},
            },
        ),
    ]
