# Generated by Django 5.0.7 on 2024-07-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_alter_funneldata_options_alter_funnelstage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callcolumns',
            options={'verbose_name': 'Модель столбцов', 'verbose_name_plural': 'Столбцы результатов первичных звонков'},
        ),
        migrations.AlterField(
            model_name='callrows',
            name='rows',
            field=models.CharField(max_length=100, unique=True, verbose_name='Строка описание причины'),
        ),
    ]
