# Generated by Django 5.0.7 on 2024-08-03 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_alter_callcolumns_options_alter_callrows_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='HhInsights_Rows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.CharField(max_length=100, unique=True, verbose_name='Строка работодателей и резюме')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HhInsights_rows', to='table.recruitmentfunnel', verbose_name='Отчетный период')),
            ],
            options={
                'verbose_name': 'Строка работодателей и резюме на HH',
                'verbose_name_plural': 'Строки работодателей и резюме на HH',
            },
        ),
        migrations.CreateModel(
            name='HhInsights_Columns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('columns', models.IntegerField(default=0, verbose_name='Значение')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HhInsights_Columns', to='table.recruitmentfunnel', verbose_name='Отчетный период')),
                ('rows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.hhinsights_rows', verbose_name='Столбец работодателей и резюме')),
            ],
            options={
                'verbose_name': 'Модель столбцов работодателей и резюме на HH',
                'verbose_name_plural': 'Столбцы работодателей и резюме на HH',
            },
        ),
    ]
